[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/api/*"
  to = "https://xyqo-backend-production.railway.app/api/:splat"
  status = 200
  force = true

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://xyqo-backend-production.railway.app"
