providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r requirements.txt --no-cache-dir"
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
